title: "Sampling Algorithms Tutorial"
description: "A comprehensive guide to sampling algorithms with interactive notebooks"
baseurl: "" # the subpath of your site
url: "https://Sampling-Algorithms.github.io" # your GitHub Pages URL
github_username: Sampling Algorithms 
# add an mimage as icon for the site, e.g., a logo or relevant graphic
icon: /assets/images/logo.ico
# icon: 🌍 # 

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  start:
    output: true
    permalink: /start/:name/
  tools:
    output: true
    permalink: /tools/:path/
  tutorials:
    output: true
    permalink: /:collection/:name

# Default layouts
defaults:
  - scope:
      path: ""
      type: "start"
    values:
      layout: "start-tutorial"
      author: "Joel & Charlesquin"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joel & Charlesquin"
  - scope:
      path: ""
    values:
      layout: "default"
